import type { HealthData, AnalysisResult } from '@/types';

/**
 * Generates a printable HTML report and triggers a download.
 * Uses the browser's print-to-PDF capability for a clean, downloadable report.
 */
export function generateReport(
  data: HealthData,
  result: AnalysisResult,
  userName?: string,
): void {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const riskColor =
    result.riskLevel === 'low' ? '#10b981' :
    result.riskLevel === 'moderate' ? '#f59e0b' : '#f43f5e';

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Q-Dx Health Risk Report — ${date}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; background: #f8fafc; line-height: 1.6; }
  .header { background: linear-gradient(135deg, #3361ff, #8b5cf6); color: white; padding: 40px; text-align: center; }
  .header h1 { font-size: 28px; margin-bottom: 8px; }
  .header p { opacity: 0.9; font-size: 14px; }
  .container { max-width: 800px; margin: 0 auto; padding: 30px; }
  .section { background: white; border-radius: 12px; padding: 24px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  .section h2 { font-size: 18px; color: #3361ff; margin-bottom: 16px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
  .risk-score-display { text-align: center; padding: 20px; }
  .risk-score-display .score { font-size: 56px; font-weight: 700; color: ${riskColor}; }
  .risk-score-display .label { font-size: 18px; text-transform: uppercase; letter-spacing: 2px; color: ${riskColor}; font-weight: 600; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
  .stat { padding: 12px; background: #f8fafc; border-radius: 8px; }
  .stat .label { font-size: 12px; color: #64748b; text-transform: uppercase; }
  .stat .value { font-size: 16px; font-weight: 600; }
  table { width: 100%; border-collapse: collapse; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
  th { color: #64748b; font-weight: 600; text-transform: uppercase; font-size: 12px; }
  .factor { display: flex; justify-content: space-between; align-items: center; padding: 10px 0; border-bottom: 1px solid #f1f5f9; }
  .factor .name { font-weight: 600; }
  .factor .severity { padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; }
  .severity-low { background: #d1fae5; color: #065f46; }
  .severity-moderate { background: #fef3c7; color: #92400e; }
  .severity-high { background: #fee2e2; color: #991b1b; }
  .recs li { margin-bottom: 8px; padding-left: 8px; }
  .disclaimer { background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 16px; margin: 20px 0; font-size: 13px; color: #92400e; }
  .footer { text-align: center; padding: 20px; color: #94a3b8; font-size: 12px; }
  .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
  .metric-box { background: #f8fafc; border-radius: 8px; padding: 16px; text-align: center; }
  .metric-box .title { font-size: 13px; color: #64748b; margin-bottom: 4px; }
  .metric-box .value { font-size: 22px; font-weight: 700; }
  @media print { .no-print { display: none; } body { background: white; } }
</style>
</head>
<body>
  <div class="header">
    <h1>Q-Dx Health Risk Assessment Report</h1>
    <p>Hybrid Quantum-Classical Machine Learning Analysis</p>
    <p style="margin-top:8px;font-size:13px;">${date}${userName ? ' · ' + userName : ''}</p>
  </div>

  <div class="container">
    <div class="disclaimer">
      <strong>Research Prototype — Not a Medical Diagnosis.</strong> This report is generated by a
      research prototype combining classical and quantum machine learning for illustrative purposes.
      The scores and analysis are for educational demonstration only and should not be used as a
      substitute for professional medical advice, diagnosis, or treatment.
    </div>

    <div class="section">
      <h2>Risk Assessment Summary</h2>
      <div class="risk-score-display">
        <div class="score">${result.riskScore}/100</div>
        <div class="label">${result.riskLevel} Risk</div>
      </div>
      <div class="grid">
        <div class="stat"><div class="label">Classical ML Score</div><div class="value">${result.classicalScore}/100</div></div>
        <div class="stat"><div class="label">Quantum ML Score</div><div class="value">${result.quantumScore}/100</div></div>
      </div>
    </div>

    <div class="section">
      <h2>Health Data Summary</h2>
      <div class="grid">
        <div class="stat"><div class="label">Age</div><div class="value">${data.age} years</div></div>
        <div class="stat"><div class="label">Gender</div><div class="value">${data.gender}</div></div>
        <div class="stat"><div class="label">BMI</div><div class="value">${data.bmi.toFixed(1)}</div></div>
        <div class="stat"><div class="label">Blood Pressure</div><div class="value">${data.bloodPressureSystolic}/${data.bloodPressureDiastolic} mmHg</div></div>
        <div class="stat"><div class="label">Heart Rate</div><div class="value">${data.heartRate} bpm</div></div>
        <div class="stat"><div class="label">Glucose</div><div class="value">${data.glucose} mg/dL</div></div>
        <div class="stat"><div class="label">Cholesterol</div><div class="value">${data.cholesterol} mg/dL</div></div>
        <div class="stat"><div class="label">Smoking</div><div class="value">${data.smoking ? 'Yes' : 'No'}</div></div>
        <div class="stat"><div class="label">Physical Activity</div><div class="value">${data.physicalActivity}</div></div>
        <div class="stat"><div class="label">Sleep</div><div class="value">${data.sleepHours} hours</div></div>
        <div class="stat"><div class="label">Alcohol</div><div class="value">${data.alcohol}</div></div>
        <div class="stat"><div class="label">Family History</div><div class="value">${data.familyHistory ? 'Yes' : 'No'}</div></div>
      </div>
    </div>

    <div class="section">
      <h2>Model Performance Comparison (Demo / Illustrative)</h2>
      <table>
        <thead><tr><th>Metric</th><th>Classical ML</th><th>Quantum ML</th></tr></thead>
        <tbody>
          <tr><td>Accuracy</td><td>${result.modelMetrics.classical.accuracy}%</td><td>${result.modelMetrics.quantum.accuracy}%</td></tr>
          <tr><td>Precision</td><td>${result.modelMetrics.classical.precision}%</td><td>${result.modelMetrics.quantum.precision}%</td></tr>
          <tr><td>Recall</td><td>${result.modelMetrics.classical.recall}%</td><td>${result.modelMetrics.quantum.recall}%</td></tr>
          <tr><td>F1 Score</td><td>${result.modelMetrics.classical.f1}%</td><td>${result.modelMetrics.quantum.f1}%</td></tr>
          <tr><td>ROC-AUC</td><td>${result.modelMetrics.classical.roc_auc}%</td><td>${result.modelMetrics.quantum.roc_auc}%</td></tr>
        </tbody>
      </table>
    </div>

    <div class="section">
      <h2>Key Risk Factors</h2>
      ${result.riskFactors.map(f => `
      <div class="factor">
        <div>
          <div class="name">${f.name}</div>
          <div style="font-size:13px;color:#64748b;">${f.description}</div>
          <div style="font-size:12px;color:#94a3b8;margin-top:2px;">Current: ${f.value}</div>
        </div>
        <span class="severity severity-${f.severity}">${f.severity}</span>
      </div>`).join('')}
    </div>

    <div class="section">
      <h2>Recommendations</h2>
      <ul class="recs">
        ${result.recommendations.map(r => `<li>${r}</li>`).join('')}
      </ul>
    </div>

    <div class="footer">
      <p>Generated by Q-Dx — Hybrid Quantum Machine Learning for Early Disease Risk Detection</p>
      <p>SIH 2026 Research Prototype · ${date}</p>
      <p style="margin-top:4px;">Research Prototype — Not a Medical Diagnosis</p>
    </div>
  </div>

  <script>
    window.onload = function() { window.print(); };
  </script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (!win) {
    // Fallback: download the file
    const a = document.createElement('a');
    a.href = url;
    a.download = `qdx-report-${Date.now()}.html`;
    a.click();
  }
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
