import { useEffect, useState } from 'react';
import {
  AlertCircle, ArrowRight, Atom, Brain, CheckCircle2,
  Cpu, Download, FileText, GitCompare, Info, Lightbulb,
  Sparkles, TrendingUp,
} from 'lucide-react';
import type { HealthData, AnalysisResult, RiskLevel } from '@/types';
import { navigate } from '@/lib/router';
import { generateReport } from '@/lib/report';
import { Disclaimer } from '@/components/Disclaimer';
import { RiskGauge } from '@/components/RiskGauge';
import { BarChart, ComparisonBar } from '@/components/Charts';
import { useAuth } from '@/context/AuthContext';

const levelInfo: Record<RiskLevel, { title: string; description: string; color: string }> = {
  low: {
    title: 'Low Risk Profile',
    description: 'Your health metrics indicate a relatively low risk of chronic disease. Maintain your healthy habits and continue regular check-ups.',
    color: 'text-emerald-500',
  },
  moderate: {
    title: 'Moderate Risk Profile',
    description: 'Some of your health metrics suggest moderate risk. Consider lifestyle adjustments and discuss these results with your healthcare provider.',
    color: 'text-amber-500',
  },
  high: {
    title: 'High Risk Profile',
    description: 'Several health metrics indicate elevated risk. We strongly recommend consulting a healthcare professional for a comprehensive evaluation.',
    color: 'text-rose-500',
  },
};

export function ResultsPage() {
  const { user } = useAuth();
  const [data, setData] = useState<HealthData | null>(null);
  const [result, setResult] = useState<AnalysisResult | null>(null);

  useEffect(() => {
    const storedData = sessionStorage.getItem('qdx-health-data');
    const storedResult = sessionStorage.getItem('qdx-analysis-result');
    if (!storedData || !storedResult) {
      navigate('/assessment');
      return;
    }
    setData(JSON.parse(storedData) as HealthData);
    setResult(JSON.parse(storedResult) as AnalysisResult);
  }, []);

  if (!data || !result) return null;

  const info = levelInfo[result.riskLevel];
  const classicalData = [
    { label: 'Classical', value: result.classicalScore },
    { label: 'Quantum', value: result.quantumScore },
    { label: 'Combined', value: result.riskScore },
  ];

  return (
    <div className="bg-mesh min-h-screen">
      <div className="container-app px-4 sm:px-6 lg:px-8 py-12">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-brand-50 dark:bg-brand-950/40 border border-brand-200 dark:border-brand-900 mb-4">
              <Sparkles className="w-4 h-4 text-brand-500" />
              <span className="text-sm font-medium text-brand-700 dark:text-brand-300">Analysis Complete</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-display font-bold text-slate-900 dark:text-white">
              Your Risk Assessment Results
            </h1>
            <p className="mt-3 text-slate-600 dark:text-slate-400">
              Generated by the Q-Dx Hybrid Quantum-Classical ML Pipeline
            </p>
          </div>

          <Disclaimer variant="card" />

          {/* Main Results Grid */}
          <div className="grid lg:grid-cols-3 gap-6 mt-8">
            {/* Risk Score Card */}
            <div className="glass-card p-8 flex flex-col items-center justify-center lg:col-span-1">
              <RiskGauge score={result.riskScore} level={result.riskLevel} size={220} />
              <div className="mt-4 text-center">
                <h2 className={`text-lg font-display font-semibold ${info.color}`}>{info.title}</h2>
                <p className="text-sm text-slate-600 dark:text-slate-400 mt-2 leading-relaxed">
                  {info.description}
                </p>
              </div>
            </div>

            {/* Score Comparison */}
            <div className="glass-card p-6 lg:col-span-2">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-2">
                  <TrendingUp className="w-5 h-5 text-brand-500" />
                  <h2 className="text-lg font-display font-semibold text-slate-900 dark:text-white">
                    Model Score Comparison
                  </h2>
                </div>
                <button onClick={() => navigate('/comparison')} className="btn-ghost text-sm">
                  <GitCompare className="w-4 h-4" />
                  Full Comparison
                </button>
              </div>

              <BarChart data={classicalData} height={180} color="from-brand-500 to-accent-500" />

              <div className="mt-6 grid grid-cols-2 gap-4">
                <div className="p-4 rounded-xl bg-brand-50 dark:bg-brand-950/30 border border-brand-200 dark:border-brand-900">
                  <div className="flex items-center gap-2 mb-2">
                    <Cpu className="w-4 h-4 text-brand-500" />
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">Classical ML Score</span>
                  </div>
                  <div className="text-3xl font-display font-bold text-brand-600 dark:text-brand-400">
                    {result.classicalScore}<span className="text-lg text-slate-400">/100</span>
                  </div>
                </div>
                <div className="p-4 rounded-xl bg-accent-50 dark:bg-accent-950/30 border border-accent-200 dark:border-accent-900">
                  <div className="flex items-center gap-2 mb-2">
                    <Atom className="w-4 h-4 text-accent-500" />
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">Quantum ML Score</span>
                  </div>
                  <div className="text-3xl font-display font-bold text-accent-600 dark:text-accent-400">
                    {result.quantumScore}<span className="text-lg text-slate-400">/100</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Key Risk Factors */}
          <div className="glass-card p-6 mt-6">
            <div className="flex items-center gap-2 mb-6">
              <AlertCircle className="w-5 h-5 text-amber-500" />
              <h2 className="text-lg font-display font-semibold text-slate-900 dark:text-white">
                Key Risk Factors
              </h2>
              <span className="text-xs text-slate-500 dark:text-slate-400 ml-auto">
                Top contributing factors identified by the hybrid model
              </span>
            </div>

            <div className="grid sm:grid-cols-2 gap-4">
              {result.riskFactors.map((factor, i) => (
                <div key={i} className="p-4 rounded-xl border border-slate-200 dark:border-slate-700 hover:shadow-md transition-shadow duration-200">
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <div className={`w-2 h-2 rounded-full ${
                        factor.severity === 'high' ? 'bg-rose-500' :
                        factor.severity === 'moderate' ? 'bg-amber-500' : 'bg-emerald-500'
                      }`} />
                      <h3 className="font-semibold text-slate-900 dark:text-white">{factor.name}</h3>
                    </div>
                    <span className={`badge ${
                      factor.severity === 'high' ? 'badge-high' :
                      factor.severity === 'moderate' ? 'badge-moderate' : 'badge-low'
                    } capitalize`}>
                      {factor.severity}
                    </span>
                  </div>
                  <p className="text-sm text-slate-600 dark:text-slate-400 mb-2">{factor.description}</p>
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-slate-500 dark:text-slate-400">Current: <span className="font-mono font-medium text-slate-700 dark:text-slate-300">{factor.value}</span></span>
                    <span className="text-slate-500 dark:text-slate-400">Contribution: <span className="font-mono font-medium text-slate-700 dark:text-slate-300">{factor.contribution}%</span></span>
                  </div>
                  <div className="mt-2 h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full ${
                        factor.severity === 'high' ? 'bg-rose-500' :
                        factor.severity === 'moderate' ? 'bg-amber-500' : 'bg-emerald-500'
                      }`}
                      style={{ width: `${factor.contribution}%`, transition: 'width 1s ease-out' }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Feature Importance */}
          <div className="grid lg:grid-cols-2 gap-6 mt-6">
            <div className="glass-card p-6">
              <div className="flex items-center gap-2 mb-6">
                <Brain className="w-5 h-5 text-accent-500" />
                <h2 className="text-lg font-display font-semibold text-slate-900 dark:text-white">
                  Feature Importance
                </h2>
              </div>
              <div className="space-y-3">
                {result.featureImportance.slice(0, 8).map((f, i) => (
                  <div key={i}>
                    <div className="flex items-center justify-between text-sm mb-1">
                      <span className="text-slate-700 dark:text-slate-300">{f.feature}</span>
                      <span className="font-mono text-slate-500 dark:text-slate-400">{f.importance}%</span>
                    </div>
                    <div className="h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                      <div
                        className="h-full rounded-full bg-gradient-to-r from-brand-500 to-accent-500"
                        style={{ width: `${f.importance * 5}%`, transition: 'width 1s ease-out' }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Recommendations */}
            <div className="glass-card p-6">
              <div className="flex items-center gap-2 mb-6">
                <Lightbulb className="w-5 h-5 text-amber-500" />
                <h2 className="text-lg font-display font-semibold text-slate-900 dark:text-white">
                  Recommendations
                </h2>
              </div>
              <ul className="space-y-3">
                {result.recommendations.map((rec, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" />
                    <span className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Quick Metrics Comparison */}
          <div className="glass-card p-6 mt-6">
            <div className="flex items-center gap-2 mb-6">
              <GitCompare className="w-5 h-5 text-brand-500" />
              <h2 className="text-lg font-display font-semibold text-slate-900 dark:text-white">
                Model Performance Overview
              </h2>
              <span className="badge bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300 ml-auto">
                Demo / Illustrative
              </span>
            </div>
            <div className="space-y-4">
              <ComparisonBar label="Accuracy" classical={result.modelMetrics.classical.accuracy} quantum={result.modelMetrics.quantum.accuracy} />
              <ComparisonBar label="Precision" classical={result.modelMetrics.classical.precision} quantum={result.modelMetrics.quantum.precision} />
              <ComparisonBar label="Recall" classical={result.modelMetrics.classical.recall} quantum={result.modelMetrics.quantum.recall} />
              <ComparisonBar label="F1 Score" classical={result.modelMetrics.classical.f1} quantum={result.modelMetrics.quantum.f1} />
              <ComparisonBar label="ROC-AUC" classical={result.modelMetrics.classical.roc_auc} quantum={result.modelMetrics.quantum.roc_auc} />
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center mt-8">
            <button
              onClick={() => generateReport(data, result, user?.email)}
              className="btn-primary"
            >
              <Download className="w-5 h-5" />
              Download Report
            </button>
            <button onClick={() => navigate('/explain')} className="btn-secondary">
              <Info className="w-5 h-5" />
              View Explainable AI
            </button>
            <button onClick={() => navigate('/assessment')} className="btn-secondary">
              <ArrowRight className="w-5 h-5" />
              New Assessment
            </button>
          </div>

          <div className="mt-8 text-center">
            <p className="text-xs text-slate-500 dark:text-slate-500 inline-flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5" />
              Research Prototype — Not a Medical Diagnosis
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
